Aplicaciones/Protocolo_Metodos/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path("protocolo_metodos/",views.protocolo_metodos, name="protocolo_metodos"),
    path("crear_protocolo_metodos/", views.crear_protocolo_metodos, name="crear_protocolo_metodos"),
    path("configuracion_protocolo_metodos/", views.configuracion_protocolo_metodos, name="configuracion_protocolo_metodos"),
    path("editar_parametro/<int:pk>/", views.editar_parametro, name="editar_parametro"),
    path("crear_metodologia/", views.crear_metodologia, name="crear_metodologia"),
    path("definir_estado/", views.definir_estado, name="definir_estado"),
    path("crear_ensayo/", views.crear_ensayo, name="crear_ensayo"),
    path("insumosDelProceso/", views.insumosDelProceso, name="insumosDelProceso"),
    path("editar_protocolo_metodos/<int:pk>/", views.editar_protocolo_metodos, name="editar_protocolo_metodos"),
    path("crear_cliente/", views.crear_cliente, name="crear_cliente"),
    path("sistemas/", views.sistemas, name="sistemas"),
    path("celdas/", views.celdas, name="celdas"),
    path("metodos/", views.metodos, name="metodos"),
    path("tipo_muestra/", views.tipo_muestra, name="tipo_muestra"),
    path("etapas/", views.etapas, name="etapas"),
    #path("invalidar_secuencias/", views.invalidar_secuencias, name="invalidar_secuencias"),
    path("viavilidad_proceso/", views.viavilidad_proceso, name="viavilidad_proceso"),




    #path("editar_protocolo_metodos/accion_editar_protocolo_metodos/<int:id>/", views.accion_editar_protocolo_metodos, name="accion_editar_protocolo_metodos"),
    path("revisar_protocolo_metodos/<int:pk>/", views.revisar_protocolo_metodos, name="revisar_protocolo_metodos"),
    path("detalles_protocolo_metodos/", views.detalles_protocolo_metodos, name="detalles_protocolo_metodos"),
    path("subparametro/", views.subparametro, name="subparametro"),
    path("titulo_parametro/", views.titulo_parametro, name="titulo_parametro"),
    path("muestras/", views.muestras, name="muestras"),
    path("ingresar_muestras/", views.ingresar_muestras, name="ingresar_muestras"),
    path("editar_muestras/<int:pk>/", views.editar_muestras, name="editar_muestras"),
    path("duplicar_muestras/<int:pk>/", views.duplicar_muestras, name="duplicar_muestras"),
    path("editar_titulo_parametro/<int:pk>/", views.editar_titulo_parametro, name="editar_titulo_parametro"),
    path("editar_subparametro/<int:pk>/", views.editar_subparametro, name="editar_subparametro"),
    path("editar_definir_estado/<int:pk>/", views.editar_definir_estado, name="editar_definir_estado"),
    path("editar_insumosDelProceso/<int:pk>/", views.editar_insumosDelProceso, name="editar_insumosDelProceso"),
    path("editar_ensayo/<int:pk>/", views.editar_ensayo, name="editar_ensayo"),
    path("editar_metodologia/<int:pk>/", views.editar_metodologia, name="editar_metodologia"),
    path("editar_cliente/<int:pk>/", views.editar_cliente, name="editar_cliente"),
    path("editar_sistemas/<int:pk>/", views.editar_sistemas, name="editar_sistemas"),
    path("editar_celdas/<int:pk>/", views.editar_celdas, name="editar_celdas"),
    path("editar_metodos/<int:pk>/", views.editar_metodos, name="editar_metodos"),
    path("editar_tipo_muestra/<int:pk>/", views.editar_tipo_muestra, name="editar_tipo_muestra"),
    path("editar_etapas/<int:pk>/", views.editar_etapas, name="editar_etapas"),
    #path("editar_invalidar_secuencias/<int:pk>/", views.editar_invalidar_secuencias, name="editar_invalidar_secuencias"),
    path("editar_viavilidad_proceso/<int:pk>/", views.editar_viavilidad_proceso, name="editar_viavilidad_proceso"),



   
]

MONSTER_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from MONSTER_APP.views import inicio, inicioAdmin,adm_inicio
from django.conf.urls import handler404
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static
#from Aplicaciones.perfiles.views import SignUpView, BienvenidaView,SignInView,SignOutView
#urlpatterns = patterns("", url(r"^admin/", include(admin.site.urls)),)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [

] + staticfiles_urlpatterns()

urlpatterns = [
    ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = [
    
    #path('', include('admin_material.urls')),
    #path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    #path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path("admin/", admin.site.urls),
    path("", inicio, name="inicio"),
    path("adm/", inicioAdmin, name="inicio-admin"),
    path("adm_inicio/", adm_inicio, name="adm_inicio"),
    path("", include("Aplicaciones.Protocolo_Metodos.urls")),
    path("", include("Aplicaciones.Secuencias.urls")),
    path("", include("Aplicaciones.Protocolo_Muestras.urls")),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path("select2/", include("django_select2.urls")),
    path("", include("Aplicaciones.perfiles.urls")),



 

    #path("incia-sesion/", SignOutView.as_view(), name="inicio-sign_out"),

    

]


    

Aplicaciones/Protocolo_Metodos/models.py
from django.db import models
from django.conf import settings
#from datetime import datetime
import datetime
from django.contrib.auth.models import User
# importing the model
# from geeks app


# Create your models here.
class Tipo_muestra(models.Model):
   
    tipo_muestra=models.CharField(verbose_name="Tipo de muestra", max_length=90, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.tipo_muestra) 
    


class Ensayo(models.Model):
   
    nombre_ensayo=models.CharField(verbose_name="Ensayo", max_length=90, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.nombre_ensayo) 
    
class Metodo(models.Model):
    codigo_metodo=models.CharField(verbose_name="código", max_length=90, unique=True)
    nombre_metodo=models.CharField(verbose_name="Nombre", max_length=90, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.codigo_metodo)     
    #11
class Etapa(models.Model):
    nombre_etapa=models.CharField(verbose_name="Etapa", max_length=90)
    ensayo=models.ForeignKey(to=Ensayo, on_delete=models.CASCADE, verbose_name="Ensayo", null=True, blank=False)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['nombre_etapa', 'ensayo'], name='etapa'),
        ]
    def etapa(self):
        return "{} {}".format(self.nombre_etapa, self.ensayo)    
    def __str__(self):    
        return str(self.etapa())      

class EstadoProtocolo(models.Model):
   
    estado_protocolos=models.CharField(verbose_name="Estado Protocolos", max_length=90)
    estado_motivo=models.CharField(verbose_name="Motivo del estado", max_length=90, blank=True, null=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")
    def estado_protocolo(self):
        return "{} {}".format(self.estado_protocolos, self.estado_motivo)    
   
    def __str__(self):    

        return str(self.estado_protocolo())   
           
class Metodologia(models.Model):
    
    nombre_metodologia=models.CharField(verbose_name="Metodologia", max_length=90, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):
         return(self.nombre_metodologia) 
    
class Subparametro(models.Model):
    
    nombre_subparametro=models.CharField(max_length=90, verbose_name="Subparametro", blank=True, null=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  


    def nombre_subparamtro_completo(self):
        return "{}".format(self.nombre_subparametro.__str__())       
   
    def __str__(self):    

        return str(self.nombre_subparamtro_completo())             
class Titulo_Parametro(models.Model):
    
    titulo_parametro=models.CharField(max_length=90, verbose_name="Titulo Párametro", blank=True, null=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  

    def nombre_titulo_parametro(self):
        return "{}".format(self.titulo_parametro)    
   
    def __str__(self):    

        return str(self.nombre_titulo_parametro())
            

class Parametro(models.Model):
    nombre_titulo=models.ForeignKey(to=Titulo_Parametro, on_delete=models.CASCADE, verbose_name="Titulo Parametro", null=True, blank=False)
    #nombre_parametro=models.ForeignKey(Subparametro, on_delete=models.CASCADE, verbose_name="Nombre Parametro", null=True, blank=True, unique=True)
    nombre_parametro=models.OneToOneField(Subparametro, on_delete=models.CASCADE, verbose_name="Nombre Parametro", null=True, blank=True, unique=True)


    #class Progreso(models.TextChoices):
        #INGRESADO = "Ingresado", "INGRESADO"
        #REVISADO = "Revisado", "REVISADO"
        #IMPRESO = "Impreso", "IMPRESO"
        #AUDITADO = "Auditado", "AUDITADO"
    #status_parametro=models.CharField(max_length=90, choices=Progreso.choices, default=Progreso.INGRESADO, verbose_name="Progreso")
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
    def nombre_Parametro(self):
        return "{} {}".format(self.nombre_titulo, self.nombre_parametro)    
   
    def __str__(self):    

        return str(self.nombre_Parametro())    

  
    # <QuerySet [{'id': 1, 'nombre_subparametro': 'Analista 1 dia 1'}]
    

class Viabilidad(models.Model):
   
    nombre_viabilidad=models.CharField(verbose_name="Insumos del Proceso", max_length=90, null=True, blank=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.nombre_viabilidad)
    

class Muestras_y_Placebos(models.Model):
    fecha_ingreso=models.DateField(verbose_name="Fecha de ingreso muestra", null=True, blank=False, help_text=u"AAAA/MM/DD")
    nombre_muestra=models.CharField(max_length=300, verbose_name="nombre de Muestra/Placebo/MP")
    tipo_muestra=models.ForeignKey(to=Tipo_muestra, on_delete=models.CASCADE, verbose_name="Tipo de muestra", null=True, blank=False)
    etapa=models.ForeignKey(to=Etapa, on_delete=models.CASCADE, verbose_name="Etapa", null=True, blank=False)
    codigo_muestra_interno=models.CharField(verbose_name="CIM / LIMS", max_length=90)
    codigo_muestra_producto=models.CharField(verbose_name="Código de Producto", max_length=90)
    lote_muestra=models.CharField(verbose_name="Lote", max_length=90)
    observaciones_muestras=models.TextField(max_length=300, verbose_name="Observaciones")
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion") 
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['lote_muestra', 'etapa'], name='unique_intro'),
        ] 
    def nombre_muestras_y_placebos(self):
         return "{} {} {} {} {} {} {} {} {} {} {}".format(self.codigo_muestra_interno, self.nombre_muestra,(","), ("Código:"), self.codigo_muestra_producto,(","), ("Lote:"), self.lote_muestra,(","), ("Etapa:"), self.etapa )
    def __str__(self):    

        return str(self.nombre_muestras_y_placebos())      

class Cliente(models.Model):
   
    nombre_cliente=models.CharField(verbose_name="Cliente", max_length=90, null=True, blank=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.nombre_cliente)

class Celda(models.Model):
   
    nombre_celda=models.CharField(verbose_name="Nombre de Celda", max_length=90, null=True, blank=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")
    responsable = models.OneToOneField(User, on_delete=models.CASCADE)  
   
    def __str__(self):    

        return(self.nombre_celda)        


class Protocolos(models.Model):
     
     fecha_ingreso=models.DateField(verbose_name="Fecha de Registro", null=True, blank=False, help_text=u"AAAA/MM/DD")
     codigo=models.CharField(max_length=90, verbose_name="Código Protocolo", null=True, blank=False, unique=True)
     nombre=models.CharField(max_length=250, verbose_name="Título_del_Protocolo",  null=True, blank=False, unique=True)
     ensayo=models.ForeignKey(to=Ensayo, on_delete=models.CASCADE, verbose_name="Ensayo", null=True, blank=False)
     metodo=models.ForeignKey(to=Metodo, on_delete=models.CASCADE, verbose_name="Metodo de referencia", null=True, blank=False)
     celda=models.ForeignKey(to=Celda, on_delete=models.CASCADE, verbose_name="Celda", null=True, blank=False)
     muestras_y_Placebos=models.ManyToManyField(Muestras_y_Placebos, blank=False)

MONSTER_APP/templates/protocolo_metodos/celdas.html
{% extends "partial/body.html" %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block contenido %}
{% load bootstrap5 %}

{% include "partial/header_configuracion_protocolo_metodos.html" %}
 <!-- INICIO Cuerpo -->
        <div class="container-fluid">
        <div class="card">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6">
                <br>
                       <div class="text-right">
            <div class="input-group rounded">
                <input type="search" id="myInput" class="numberinput gj-textbox-md" placeholder="Buscar..." aria-label="Search" aria-describedby="search-addon" />
               
              </div>
        </div>
                  </div>
                  <div class="col-md-6">
                    <br>
                      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <!--<button class="btn btn-warning" data-bs-toggle="modal" data-target=".bd-example-modal-lg" data-bs-target="#crear_parametros"><span class="fa fa-plus-circle"></span>Nueva secuencia</button>-->
                        <!--<a href="{% url 'crear_secuencias' %}" class="btn btn-primary" style="background:#486af3b8"><span class="fa fa-plus-circle"></span>Nueva secuencia</a>-->

                        <button class="btn btn-primary" style="background:#486af3c7" data-bs-toggle="modal" data-bs-target="#crear_parametros"><span class="fa fa-plus-circle"></span>Nueva Celda</button>


                        </div>
              </div>
              </div>
          </div><br>
            <div class="card-body table-responsive">
              <table class="table  table-bordered display" id="example3">
                <thead class="">
                    <tr class="text-center">
                        <th class="text-center">Id</th>
                        <th class="text-center">Nombre Celda</th>
                        <th class="text-center">Responsable</th>
                        <th class="text-center">Estado</th>
                        <th class="all text-center" >Acciones</th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    {% for item in celdas.all %}
                    <tr class="text-center">
                        <td class="text-center">{{item.id}}</td>
                        <td class="text-center">{{item.nombre_celda}}</td>
                        <td class="text-center">{{item.responsable}}</td>
                        <td class="text-center">{{item.condicion}}</td>
                        <td>
                            <a href="{% url 'editar_cliente' item.pk %}" class="btn btn-primary btn-circle text-center" data-bs-target="#modal_parametros_{{ item.pk }}" data-bs-toggle="modal"><span class="fa fa-edit"></span>Editar</a>
                        </td>
                    </tr>
                    <!-- Formulario-Edicion Modal -->
<div class="modal fade" id="modal_parametros_{{ item.pk }}" tabindex="-1" aria-labelledby="modal_parametros" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="ModalLabel">Editar Celdas</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form action="{% url 'editar_celdas' item.pk %}" method="POST"> {% csrf_token %}
                <div class="mb-3">
                  <label class="form-label" for="id_nombre_celda">Celda</label>
                  <input type="text" name="nombre_celda" value="{{item.nombre_celda}}" maxlength="90" class="form-control" placeholder="Celda" title="" required="" id="id_nombre_celda">
                </div>
                <div class="mb-3"><label class="form-label" for="id_responsable">Responsable</label><select name="responsable" class="form-select" value="{{item.pk}}" title="" id="id_responsable">
                    <option value="{{item.responsable_id}}" selected="{{item.id}}">{{item.responsable}}</option>
                    {% for item2 in responsable.all %}
                    <option value="{{item2.id}}">{{item2}}</option>
                    {% endfor %}
                  </select></div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-block" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary btn-block">Guardar cambios</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  {% endfor%}
  <!-- Formulario Edicion Modal -->
</tbody>
</table>
</div>
</div>
</div>
      <!-- Formulario-Creación Modal -->
  <div class="modal fade" id="crear_parametros" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="ModalLabel">Crear Celda</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'celdas' %}" method="POST"> {% csrf_token %}
            {% bootstrap_form form layout="" %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-block" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary btn-block">Guardar</button>
        </div>
    </form>
      </div>
    </div>
  </div>
  <!-- Formulario Creación Modal -->

  <!--Data-table-->
     <script>
        new DataTable('#example3', {
         searching:false,
         "bPaginate": false,
     "bLengthChange": true,
     "bFilter": false,
     "bInfo": false,
     "bAutoWidth": true,
     "striped": false,
        });
     </script>
      <!--Data-table-->
{% endblock contenido %}

MONSTER_APP/templates/protocolo_metodos/crear_protocolo_metodos.html
{% extends "protocolo_metodos/base_crear_protocolo_metodos.html" %}
{% block contenido %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!--Advanced multiselect esasy-->
<script src="https://www.jqueryscript.net/demo/advanced-multiselect-easy/easySelect.js"></script>
  <div class="container-fluid"><br>
    
    
           <!-- Using a local copy -->

<!-- Include the default stylesheet -->


<!-- Or using a CDN -->

<!-- Include the default stylesheet -->
   
            
    <div class="row">
        <!---------------------------------------Inicio Columna 1------------------------------------------------------>
      <div class="">
        <div class="card col-12 col-lg-7" style="background-color: #1b3d70c2;margin: auto;">
          <h5 class="text-white text-center"><br>Crear Protocolo de Métodos</h5>
     </div>
        <div class="card col-12 col-lg-7" style="margin: auto;">
          <div class="row gy-1 gy-xl-2 p-4 p-xl-4">
            <form action=""  id="myModelForm" method="POST">
              {% csrf_token %}
                   
              <div class="row">
                <div class="col-md-6">
                  {{ form.fecha_ingreso|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  {{ form.codigo|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  {{ form.cliente|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  {{ form.ensayo|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  {{ form.celda|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  {{ form.metodologia|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  {{ form.metodo|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  {{ form.estado_protocolo|as_crispy_field  }}
                </div>
              </div>
              {{ form.nombre|as_crispy_field  }}
              

            {{ form.Insumos_del_Proceso|as_crispy_field  }}
            <div class="card col-md-12">
              {{ form.parametro|as_crispy_field  }}
            </div>
            <div class="card col-md-12" >
              {{ form.muestras_y_Placebos|as_crispy_field  }}
            </div>
           
            {{ form.observaciones|as_crispy_field  }}
            <div class="modal-footer">
              <a href="{% url 'muestras' %}" onclick='salir(event)' style="background-color: #7d848ec2;" class="btn btn-dark" >Cancelar</a>
              <button type="submit" onclick='confirmar(event)' class="btn btn-primary" style="background-color: #1b3d70c2;" >Guardar</button>
            </div>
          </div>
          
        </div>
      </div>
      <!---------------------------------------------Inicio Columna 2------------------------------------------------------>
     
    
       
    </form>
      {% block scripts %}
      <script>
      
        $("#id_ensayo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_metodo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_cliente").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
      </script>
      <script>
        $('select').multipleSelect();
    </script>
<script> 
$(document).ready(function() {
$('#id_parametro').css('width', '100%').multiselect(
{
  
enableFiltering: true,
filterBehavior: 'text',
buttonWidth: '100%',
enableClickableOptGroups: true,
enableCollapsibleOptGroups: true,
nonSelectedText: 'Seleccionar Parametros',
enableCaseInsensitiveFiltering: true,
includeSelectAllOption: true,
maxHeight: 300
}
);
});
</script>

s


<script> 
  $(document).ready(function() {
  $('#id_muestras_y_Placebos').css('width', '100%').multiselect(
  {
  enableFiltering: true,
  
  filterBehavior: 'text',
  buttonWidth: '100%',
  enableClickableOptGroups: true,
  enableCollapsibleOptGroups: true,
  nonSelectedText: 'Seleccionar muestras',
  enableCaseInsensitiveFiltering: true,
  includeSelectAllOption: true,
  maxHeight: 300,
  
  

  }
  );
  });
  </script>
       {% endblock scripts %}
    </div>
  </div>

 <!-- Validación de campos -->
 <script>

  
  function confirmar(event) { 
    
    event.preventDefault();
    Swal.fire({
  title: "Está seguro?",
  text: "Por favor, confirme la creación del protocolo!",
  icon: "question",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Confirmar!"
    }).then((result) => {
        if (result.isConfirmed) {
          document.getElementById('myModelForm').submit();
        }
    })
}
</script>
<script>
  function salir(event) { 
    
    event.preventDefault();
    Swal.fire({
  title: "Desea salir?",
  text: "Tu información no será guardada!",
  icon: "warning",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Confirmar",
  cancelButtonText: "Cancelar"
}).then((result) => {
        if (result.isConfirmed) {
          window.location.href = '/adm_inicio'
        }
    })
}
</script>
  <!-- validacion de campos-->

<!--
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>  
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" rel="stylesheet"/>

  {% endblock contenido %}