Aplicaciones/Secuencias/urls.py
from django.urls import path

from . import views

urlpatterns=[
   
    path("crear_secuencias/",views.crear_secuencias, name="crear_secuencias"),
    #path("editar_secuencias/<int:pk>/", views.editar_secuencias, name="editar_secuencias"),
    path("actualizar_secuencias_validadas/<int:pk>/", views.actualizar_secuencias_validadas,name="actualizar_secuencias_validadas"),
    path("cambiar_estado_ensayo/<int:pk>/", views.cambiar_estado_ensayo,name="cambiar_estado_ensayo"),
    #path("actualizar_secuencias_impresas/<int:pk>/", views.actualizar_secuencias_impresas, name="actualizar_secuencias_impresas"),
    #path("actualizar_secuencias_reportadas/<int:pk>/", views.actualizar_secuencias_reportadas, name="actualizar_secuencias_reportadas"),
    path("crear_secuencias_en_curso/",views.crear_secuencias_en_curso, name="crear_secuencias_en_curso"),
    path("editar_secuencias_en_curso/<int:pk>/", views.editar_secuencias_en_curso, name="editar_secuencias_en_curso"),
    path("agregar_otra_secuencia_parametro/<int:pk>/", views.agregar_otra_secuencia_parametro, name="agregar_otra_secuencia_parametro"),
    path("agregar_otra_secuencia_muestra/<int:pk>/", views.agregar_otra_secuencia_muestra, name="agregar_otra_secuencia_muestra"),
    path("proceso_secuencias_en_curso/",views.proceso_secuencias_en_curso, name="proceso_secuencias_en_curso"),
    path("secuencias_invalidas/",views.secuencias_invalidas, name="secuencias_invalidas"),
    path("chart_js_proceso_secuencias_en_curso/",views.chart_js_proceso_secuencias_en_curso, name="chart_js_proceso_secuencias_en_curso"),
    path("mantenimientos_periodicos/",views.mantenimientos_periodicos, name="mantenimientos_periodicos"),
    path("mantenimientos_buzos_realizados/",views.mantenimientos_buzos_realizados, name="mantenimientos_buzos_realizados"),
    path("mantenimientos_celdas_realizados/",views.mantenimientos_celdas_realizados, name="mantenimientos_celdas_realizados"),
    path("mantenimientos_test_realizados/",views.mantenimientos_test_realizados, name="mantenimientos_test_realizados"),
    path("mantenimientos_preventivo_realizado/",views.mantenimientos_preventivo_realizado, name="mantenimientos_preventivo_realizado"),
    path("calificaciones_realizadas/",views.calificaciones_realizadas, name="calificaciones_realizadas"),
    path("mantenimientos_buzos_Check_form/", views.mantenimientos_buzos_Check_form, name="mantenimientos_buzos_Check_form"),
    path("cambiar_estado_secuencias/", views.cambiar_estado_secuencias, name="cambiar_estado_secuencias"),
    path("cambiar_estado_validada_revisada/", views.cambiar_estado_validada_revisada, name="cambiar_estado_validada_revisada"),



  
]

MONSTER_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from MONSTER_APP.views import inicio, inicioAdmin,adm_inicio
from django.conf.urls import handler404
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static
#from Aplicaciones.perfiles.views import SignUpView, BienvenidaView,SignInView,SignOutView
#urlpatterns = patterns("", url(r"^admin/", include(admin.site.urls)),)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [

] + staticfiles_urlpatterns()

urlpatterns = [
    ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = [
    
    #path('', include('admin_material.urls')),
    #path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    #path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path("admin/", admin.site.urls),
    path("", inicio, name="inicio"),
    path("adm/", inicioAdmin, name="inicio-admin"),
    path("adm_inicio/", adm_inicio, name="adm_inicio"),
    path("", include("Aplicaciones.Protocolo_Metodos.urls")),
    path("", include("Aplicaciones.Secuencias.urls")),
    path("", include("Aplicaciones.Protocolo_Muestras.urls")),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path("select2/", include("django_select2.urls")),
    path("", include("Aplicaciones.perfiles.urls")),



 

    #path("incia-sesion/", SignOutView.as_view(), name="inicio-sign_out"),

    

]


    

Aplicaciones/Secuencias/models.py
from django.db import models
from django.conf import settings
from Aplicaciones.Protocolo_Metodos.models import Protocolos, Parametro, Ensayo, Muestras_y_Placebos, Metodo
from Aplicaciones.Protocolo_Muestras.models import Proceso
from Aplicaciones.perfiles.models import Perfil
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
import datetime
from django.utils import timezone



# Create your models here.



class Sistema(models.Model):
    nombre=models.CharField(max_length=250, verbose_name="Sistema",  null=True, blank=False)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
    
    def __str__(self):    

        return(self.nombre)
    

class usuario_invalidar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username   
class usuario_validar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username
           
class usuario_impresion(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username
    
class usuario_reporte(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username

class usuario_auditor(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username         
    

#

class Secuencias(models.Model):
    #order_number = models.IntegerField(primary_key=False, blank=True, null=True, default=0 )
    #fecha_Invalidez=models.DateTimeField(verbose_name="Fecha ID", null=True, blank=True, default=datetime.datetime.now)
    nombre=models.CharField(max_length=250, verbose_name="Nombre",  null=False, blank=False)
    fecha_Inicio=models.DateTimeField(verbose_name="Fecha de Inicio", null=False, blank=False)
    #hora_Inicio=models.TimeField(verbose_name="Hora de Inicio", null=True, blank=True )
    fecha_Final=models.DateTimeField(verbose_name="Fecha de Finalización", null=True, blank=True)
    #hora_Final=models.TimeField(verbose_name="Hora de Finalización", null=True, blank=True )
    protocolo=models.ForeignKey(to=Protocolos, on_delete=models.CASCADE, verbose_name="Protocolo", null=True, blank=True)
    protocolo_proceso=models.ForeignKey(to=Proceso, on_delete=models.CASCADE, verbose_name="Protocolo de Proceso", null=True, blank=True)
    sistema=models.ForeignKey(to=Sistema, on_delete=models.CASCADE, verbose_name="Sistema", null=True, blank=False)
    class Status(models.TextChoices):
        REGISTRADA = "Registrada", "REGISTRADA"
        INVALIDA = "Invalida", "INVALIDA"
        REVISADA = "Revisada", "REVISADA"
        IMPRESA = "Impresa", "IMPRESA"
        REPORTADA = "Reportada", "REPORTADA"
        AUDITADA = "Auditada", "AUDITADA"
        ENSAYO = "Ensayo", "ENSAYO"
    status=models.CharField(max_length=90, choices=Status.choices, default=Status.REGISTRADA, verbose_name="Status", null=True, blank=True)  
    class Invalidar_Secuencia(models.TextChoices):
        PROBLEMAS_EQUIPO_1 = "Problemas de equipo (Equipo presionado, Linea base defectuosa)", "PROBLEMAS_EQUIPO_1"
        PROBLEMAS_EQUIPO_2 = "Problemas de equipo (Otros: Caidas de presión, Picos fantasmas; Problemas de software/hadware...)", "PROBLEMAS_EQUIPO_2"
        PROBLEMAS_COLUMNA = "Problemas de columna", "PROBLEMAS_COLUMNA"
        INCUMPLIMIENTO_SST_1 = "Incumplimiento de System (RSD)", "INCUMPLIMIENTO_SST_1"
        INCUMPLIMIENTO_SST_2 = "Incumplimiento de System (Otros: Resolución, Asimetria, Platos teóricos, Señal ruido)", "INCUMPLIMIENTO_SST_2"
        INCUMPLIMIENTO_SST_3 = "Incumplimiento de System (Correlación)", "INCUMPLIMIENTO_SST_3"
        PROBLEMAS_FM = "Problemas de Fases Móviles (TR Corridos, FM saturada, Otros...)", "PROBLEMAS_DE_FASE_MOVIL"
        PROBLEMAS_RED = "Problemas de red", "PROBLEMAS_RED"
        PROBLEMAS_FE = "Fallas de Fluido Eléctrico", "PROBLEMAS_DE_FLUIDO_ELECTRICO"
        OTROS = "Otros (definir en observaciones)", "OTROS"
    invalidar_Secuencia=models.CharField(max_length=250, choices=Invalidar_Secuencia.choices, verbose_name="Invalidar Secuencia", null=True, blank=True)  
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion", null=True, blank=True)  
    observaciones=models.CharField(max_length=250, verbose_name="Observaciones",  null=True, blank=True)
    parametro_sq=models.ForeignKey(to=Parametro, on_delete=models.CASCADE, verbose_name="Parametro", null=True, blank=True)
    metodo=models.ForeignKey(to=Metodo, on_delete=models.CASCADE, verbose_name="Metodo", null=True, blank=True)
    #muestras=models.ManyToManyField(to=Muestras_y_Placebos, blank=False)
    muestras=models.ForeignKey(to=Muestras_y_Placebos, on_delete=models.CASCADE, verbose_name="Muestras", null=True, blank=True)
    fecha_invalidar=models.DateTimeField(verbose_name="Fecha de Invalidéz", null=True, blank=True)
    fecha_validar=models.DateTimeField(verbose_name="Fecha de Validación", null=True, blank=True)
    fecha_impresion=models.DateTimeField(verbose_name="Fecha de Impresión", null=True, blank=True)
    fecha_reporte=models.DateTimeField(verbose_name="Fecha de Reporte", null=True, blank=True)
    fecha_auditada=models.DateTimeField(verbose_name="Fecha auditada", null=True, blank=True)
    def individual():
     " This function will be called when a default value is needed.ll return a 31 length string with a-z, 0-9."
     return 'Prueba'
    #referencia=models.CharField(max_length=250, verbose_name="Referencia Reporte",  null=True, blank=True,default=individual)
    invalidar=models.CharField(max_length=250, verbose_name="Invalidada por",  null=True, blank=True)
    validar=models.CharField(max_length=250, verbose_name="Validada por",  null=True, blank=True)
    imprimir=models.CharField(max_length=250, verbose_name="Impresa",  null=True, blank=True)
    reportar=models.CharField(max_length=250, verbose_name="Reportada por",  null=True, blank=True)
    auditar=models.CharField(max_length=250, verbose_name="Auditada por",  null=True, blank=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['protocolo', 'parametro_sq', 'fecha_invalidar'], name='unique'),
            models.UniqueConstraint(fields=['protocolo_proceso', 'muestras', 'fecha_invalidar'], name='unique_intro_nue'),
        ]
    
    def nombre_Secuencia(self):
        return "{}".format(self.nombre)    
    def __str__(self):    

        return str(self.nombre_Secuencia())
    
    
class Lavado_buzo(models.Model):
    date_joined = datetime.datetime.now()
    progrmado = datetime.datetime.now() + datetime.timedelta(days=30) 
    limite_inferior = datetime.datetime.now() + datetime.timedelta(days=59.8) 
    limite_superior = datetime.datetime.now() + datetime.timedelta(days=60.9) 
    progrmado_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=60.8) 
    limite_inferior_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=5) 
    limite_superior_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=7) 
    progrmado_calificacion = datetime.datetime.now() + datetime.timedelta(days=60.8)
    limite_inferior_calificacion = datetime.datetime.now() + datetime.timedelta(days=5)
    limite_superior_calificacion = datetime.datetime.now() + datetime.timedelta(days=7)
    sistema=models.ForeignKey(to=Sistema, on_delete=models.CASCADE, verbose_name="Sistema", null=True, blank=False)
    fecha_lavado_buzo=models.DateField(verbose_name="Fecha de lavado de buzos", null=True, blank=True, default=progrmado)
    fecha_lavado_celda=models.DateField(verbose_name="Fecha de lavado de celda", null=True, blank=True, default=progrmado)
    fecha_test_diagnostico=models.DateField(verbose_name="Fecha del test", null=True, blank=True, default=progrmado)
    fecha_mantenimiento=models.DateField(verbose_name="Fecha del Mantenimiento", null=True, blank=True, default=progrmado_mantenimiento) 
    fecha_calificacion=models.DateField(verbose_name="Fecha de la calificación", null=True, blank=True, default=progrmado_mantenimiento) 
    fecha_alerta_inferior=models.DateField(verbose_name="Fecha de alerta inferior", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior=models.DateField(verbose_name="Fecha de alerta superior", null=True, blank=True, default=limite_superior)
    fecha_alerta_inferior_celda=models.DateField(verbose_name="Fecha de alerta inferior celda", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior_celda=models.DateField(verbose_name="Fecha de alerta superior celda", null=True, blank=True, default=limite_superior)
    fecha_alerta_inferior_test=models.DateField(verbose_name="Fecha de alerta inferior test", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior_test=models.DateField(verbose_name="Fecha de alerta superior test", null=True, blank=True, default=limite_superior) 
    fecha_alerta_inferior_mantenimiento=models.DateField(verbose_name="Fecha de alerta inferior mantenimiento", null=True, blank=True, default=limite_inferior_mantenimiento) 
    fecha_alerta_superior_mantenimiento=models.DateField(verbose_name="Fecha de alerta superior mantenimiento", null=True, blank=True, default=limite_superior_mantenimiento) 

Aplicaciones/Secuencias/forms.py
from django import forms
from django.contrib import admin
from django.forms.widgets import NumberInput
from django.contrib.admin.widgets import AutocompleteSelect
from django_select2 import forms as s2forms
from .models import Protocolos,Sistema,Parametro,Lavado_buzo
from django.core.exceptions import ValidationError
from django.core import validators




#from simple_autocomplete.widgets import AutoCompleteWidget


from .models import Secuencias

class secuenciasForm(forms.ModelForm):
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'rows':5}), required=True)
    #invalidez = forms.ModelChoiceField(
    #empty_label= ("Seleccione el motivo"),
    #queryset=Invalidar_Secuencia.objects.all(),
    #required=False)
    #fecha_Inicio = forms.DateField(widget=forms.DateInput(format='%d.%B.%Y'),
        #input_formats=['%d.%B.%Y']
    #)
    #fecha_Inicio = forms.DateTimeField(
        #label="Fecha de Inicio",
        #required=True,
       # widget=forms.DateTimeInput(format=["%Y-%m-%d %H:%M:%S"], attrs={"type": "datetime-local"}),
        #input_formats=["%Y-%m-%d %H:%M:%S"]
    #)
    
   
    class Meta:
        model=Secuencias
        fields = '__all__'
        #exclude=["condicion"] 

    #def clean_observaciones(self):
        #cleaned_data = super(secuenciasForm, self).clean()
        #observaciones=cleaned_data.get("Observaciones")
      
        #if observaciones[0].lower() != 'd':
        
        
            #raise forms.ValidationError("PILAS")
        #return observaciones   
class buzosForm(forms.ModelForm):
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'rows':8}), required=True)
    class Meta:
        model= Lavado_buzo
        fields = '__all__'
        exclude = ["condicion"]

MONSTER_APP/templates/secuencias/editar_secuencias_en_curso.html
{% extends "partial/body.html" %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block contenido %}
{% load bootstrap5 %}
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.4/components/contacts/contact-1/assets/css/contact-1.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!--Advanced multiselect esasy-->
<script src="https://www.jqueryscript.net/demo/advanced-multiselect-easy/easySelect.js"></script>

 <!-- Contact 1 - Bootstrap Brain Component -->

<section class="bg-light py-3 py-md-3">  


  <div class="container">
    
  
    <div class="row justify-content-lg-center">
     
      <div class="col-12 col-lg-7">
        <div class="shadow-sm overflow-hidden rounded " style="background-color: #1b3d70c2; ">
          <h5 class="text-white text-center  "><br>Editar Secuencia</h5>
     </div>
        <div class="bg-white border rounded shadow-sm overflow-hidden">

          <form action="" iname="myFormEditar" id="myFormEditar" method="POST">    {% csrf_token %}
            {% for item in sq  %}
          
            <div class="row gy- gy-xl-1 p- p-xl-4">
              <div class="col-12 col-md-6">
                <label>Fecha de Inicio</label>
                <input value="{{item.fecha_Inicio|date:'Y-m-d H:i'}}" type="datetime-local" name="fecha_Inicio" class="numberinput form-control gj-textbox-md" id="fecha_Inicio" width="" data-datepicker="true"> 
            </div>
              <div class="col-12 col-md-6">
                <label class="form-label">
                    Nombre
                </label>
                <input type="text" name="nombre" maxlength="250" value="{{item.nombre}}" class="numberinput form-control gj-textbox-md" id="id_nombre">            </div>
            <div class="col-12 col-md-12">
                {{ form.sistema|as_crispy_field  }}
            </div>
           
            {% if item.protocolo_proceso.id == None and item.metodo.id == None %}
                       <!--PROTOCOLO METODO-->
                       <label class="form-label" >Protocolo de Método</label>
                       <div class="form-group" >
                         <select   name="protocolo" style="width: 100%;" required="" id="id_protocolo" class="protocoloMetodoEdicion">
                             <option value="{{item.protocolo_id}}">{{item.protocolo}}</option>
                             {% for item1 in protocolos.all %}
                             {% if item1.estado_protocolo.id == 1 and item1.condicion == "Activo"  %}
                             <option value="{{item1.id}}">{{item1}}</option>
                           {% endif %}
                           {% endfor %}
                           </select>
                       </div><br>
                     <!--PROTOCOLO METODO-->
                <div class="col-12 col-md-12">
                {{ form.parametro_sq|as_crispy_field  }}
            </div>
            {% endif %}
            {% if item.protocolo.id == None and item.metodo.id == None %}
                      <!--PROTOCOLO PROCESO-->
                      <label class="form-label">Protocolo de Proceso</label>
                      <div class="form-group" >
                        <select name="protocolo_proceso" style="width: 100%;" required="" id="id_protocolo_proceso" class="protocoloProcesoEdicion" >
                          <option value="{{item.protocolo_proceso_id}}">{{item.protocolo_proceso}}</option>
                          {% for item1 in protocolo_proceso.all %}
                          {% if item1.estado_del_proceso.id == 1 and item1.condicion == "Activo"  %}
                          <option value="{{item1.id}}">{{item1}}</option>
                          {% endif %}
                          {% endfor %}
                        </select>
                      </div><br>
                    <!--PROTOCOLO PROCESO-->  
            {% endif %}
            {% if item.protocolo.id == None and item.protocolo_proceso.id == None %}
            <div class="col-12 col-md-12">
                {{ form.metodo|as_crispy_field  }}
            </div>
            {% endif %}
            {% if item.protocolo.id == None %}
            <div class="col-12 col-md-12">
                {{ form.muestras|as_crispy_field  }}
            </div>
            {% endif %}
            <div class="col-12 col-md-12">
                <label>Observaciones</label>
                <textarea name="observaciones" value="{{item.observaciones}}" cols="40" rows="4" class="numberinput form-control gj-textbox-md" id="id_observaciones" required="">{{item.observaciones}}</textarea><br>
             </div>
                <!--FECHA INVALIDAR PARA EVITAR REGISTROS DUPLICADOS--> 
                <input value="0001-01-01" type="text" name="fecha_invalidar" class="numberinput form-control gj-textbox-md " id="fecha_invalidar" width="" data-datepicker="true" style="display: none;"> 
                <!--FECHA INVALIDAR PARA EVITAR REGISTROS DUPLICADOS--> 
            {% endfor %}
         
            <div class="modal-footer">
                <a href="{% url 'crear_secuencias_en_curso' %}" onclick='salir(event)' type="submit" class="btn btn-dark " style="background-color: #7d848ec2;" >Cancelar</a>
                <button type="submit" onclick='confirmar(event)' class="btn btn-primary" style="background-color: #1b3d70c2;" >Guardar</button>
            </div>

             
          </form>

        </div>
      </div>
    </div>
  </div>
</section>

<!-- Margen Final -->
<script>
  $("#id_muestras").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_parametro_sq").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_protocolo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_sistema").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_metodo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_protocolo_proceso").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});





</script>
<!-- Validación de campos -->
<script>
    function salir(event) { 
      event.preventDefault();
      Swal.fire({
    title: "Desea salir?",
    text: "Tu información no será guardada!",
    icon: "warning",
    showCancelButton: true,
    confirmButtonColor: "#3085d6",
    cancelButtonColor: "#d33",
    confirmButtonText: "Confirmar",
    cancelButtonText: "Cancelar"
  }).then((result) => {
          if (result.isConfirmed) {
            window.location.href = '/crear_secuencias_en_curso'
          }
      })
  }
  </script>
<script>
  function confirmar(event) { 
    
    let nombre = document.forms["myFormEditar"]["nombre"].value;
    let observaciones = document.forms["myFormEditar"]["observaciones"].value;
    
if (nombre == "") {
alert("El nombre de la secuencia es obligatorio!");
event.preventDefault();
return
}
if (observaciones == "") {
alert("El campo de observaciones es obligatorio!");
event.preventDefault();
return
}
if (nombre.length <= 8) {
alert("El nombre de secuencia es muy corto!");
event.preventDefault();
return  
}

    event.preventDefault();
    Swal.fire({
  title: "Está seguro?",
  text: "Por favor, confirme la edición de secuencia!",
  icon: "question",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Confimar!"
    }).then((result) => {
        if (result.isConfirmed) {
          document.getElementById('myFormEditar').submit();
        }
    })
}
</script>
  <!-- validacion de campos-->


{% endblock contenido %}







<!-- Margen Inicio -->