MONSTER_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from MONSTER_APP.views import inicio, inicioAdmin,adm_inicio
from django.conf.urls import handler404
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static
#from Aplicaciones.perfiles.views import SignUpView, BienvenidaView,SignInView,SignOutView
#urlpatterns = patterns("", url(r"^admin/", include(admin.site.urls)),)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [

] + staticfiles_urlpatterns()

urlpatterns = [
    ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = [
    
    #path('', include('admin_material.urls')),
    #path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    #path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path("admin/", admin.site.urls),
    path("", inicio, name="inicio"),
    path("adm/", inicioAdmin, name="inicio-admin"),
    path("adm_inicio/", adm_inicio, name="adm_inicio"),
    path("", include("Aplicaciones.Protocolo_Metodos.urls")),
    path("", include("Aplicaciones.Secuencias.urls")),
    path("", include("Aplicaciones.Protocolo_Muestras.urls")),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path("select2/", include("django_select2.urls")),
    path("", include("Aplicaciones.perfiles.urls")),



 

    #path("incia-sesion/", SignOutView.as_view(), name="inicio-sign_out"),

    

]


    

Aplicaciones/Protocolo_Muestras/models.py
from django.db import models
from Aplicaciones.Protocolo_Metodos.models import Ensayo,Metodologia, Celda, Cliente, Muestras_y_Placebos, EstadoProtocolo, Metodo
import datetime


# Create your models here.

#3class Estado_Proceso(models.Model):
   
  #  estado_proceso=models.CharField(verbose_name="Estado del proceso", max_length=90)
   # estado_motivo=models.CharField(verbose_name="Motivo del estado", max_length=90, blank=True, null=False, unique=True)
    #class Condicion(models.TextChoices):
     #   ACTIVO = "Activo", "ACTIVO"
      #  PASIVO = "Pasivo", "PASIVO"
    #condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")
    #def estado_protocolo_proceso(self):
     #   return "{} {}".format(self.estado_proceso, self.estado_motivo)    
   
   # def __str__(self):    

    #    return str(self.estado_protocolo_proceso()) 

class ViabilidadProceso(models.Model):
   
    nombre_viabilidad=models.CharField(verbose_name="Insumos del Proceso", max_length=90, null=True, blank=False, unique=True)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
   
    def __str__(self):    

        return(self.nombre_viabilidad)
    
class Proceso(models.Model):
     fecha_ingreso=models.DateField(verbose_name="Fecha de Registro", null=True, blank=False, help_text=u"AAAA/MM/DD")
     codigo=models.CharField(max_length=90, verbose_name="Código Protocolo", null=True, blank=False, unique=True)
     nombre=models.CharField(max_length=250, verbose_name="Título_del_Protocolo",  null=True, blank=False, unique=True)
     ensayos=models.ManyToManyField(to=Ensayo, blank=False)
     celda=models.ForeignKey(to=Celda, on_delete=models.CASCADE, verbose_name="Celda", null=True, blank=False)
     muestras=models.ManyToManyField(Muestras_y_Placebos, blank=False)
     metodologia=models.ForeignKey(Metodologia, on_delete=models.CASCADE, verbose_name="metodologia", null=True, blank=False,  max_length=90)
     #parametro=models.ManyToManyField(to=Parametro, blank=False, related_name="parametro")
     Insumos_del_Proceso=models.ManyToManyField(to=ViabilidadProceso)
     cliente=models.ForeignKey(to=Cliente, on_delete=models.CASCADE, verbose_name="Cliente", null=True, blank=False)
     metodo=models.ForeignKey(to=Metodo, on_delete=models.CASCADE, verbose_name="Metodo de referencia", null=True, blank=False)
     estado_del_proceso=models.ForeignKey(to=EstadoProtocolo, on_delete=models.CASCADE, verbose_name="Estado del proceso", null=True, blank=False)
     class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
     condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
     observaciones=models.CharField(max_length=250, verbose_name="Observaciones",  null=True, blank=False)
     fecha_final=models.DateField(verbose_name="Fecha de Finalización", null=True, blank=True,default=datetime.datetime.now)

     def __str__(self):        
        return str(self.codigo)
    

Aplicaciones/Secuencias/models.py
from django.db import models
from django.conf import settings
from Aplicaciones.Protocolo_Metodos.models import Protocolos, Parametro, Ensayo, Muestras_y_Placebos, Metodo
from Aplicaciones.Protocolo_Muestras.models import Proceso
from Aplicaciones.perfiles.models import Perfil
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
import datetime
from django.utils import timezone



# Create your models here.



class Sistema(models.Model):
    nombre=models.CharField(max_length=250, verbose_name="Sistema",  null=True, blank=False)
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion")  
    
    def __str__(self):    

        return(self.nombre)
    

class usuario_invalidar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username   
class usuario_validar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username
           
class usuario_impresion(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username
    
class usuario_reporte(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username

class usuario_auditor(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    # Python 3
    def __str__(self): 
        return self.usuario.username         
    

#

class Secuencias(models.Model):
    #order_number = models.IntegerField(primary_key=False, blank=True, null=True, default=0 )
    #fecha_Invalidez=models.DateTimeField(verbose_name="Fecha ID", null=True, blank=True, default=datetime.datetime.now)
    nombre=models.CharField(max_length=250, verbose_name="Nombre",  null=False, blank=False)
    fecha_Inicio=models.DateTimeField(verbose_name="Fecha de Inicio", null=False, blank=False)
    #hora_Inicio=models.TimeField(verbose_name="Hora de Inicio", null=True, blank=True )
    fecha_Final=models.DateTimeField(verbose_name="Fecha de Finalización", null=True, blank=True)
    #hora_Final=models.TimeField(verbose_name="Hora de Finalización", null=True, blank=True )
    protocolo=models.ForeignKey(to=Protocolos, on_delete=models.CASCADE, verbose_name="Protocolo", null=True, blank=True)
    protocolo_proceso=models.ForeignKey(to=Proceso, on_delete=models.CASCADE, verbose_name="Protocolo de Proceso", null=True, blank=True)
    sistema=models.ForeignKey(to=Sistema, on_delete=models.CASCADE, verbose_name="Sistema", null=True, blank=False)
    class Status(models.TextChoices):
        REGISTRADA = "Registrada", "REGISTRADA"
        INVALIDA = "Invalida", "INVALIDA"
        REVISADA = "Revisada", "REVISADA"
        IMPRESA = "Impresa", "IMPRESA"
        REPORTADA = "Reportada", "REPORTADA"
        AUDITADA = "Auditada", "AUDITADA"
        ENSAYO = "Ensayo", "ENSAYO"
    status=models.CharField(max_length=90, choices=Status.choices, default=Status.REGISTRADA, verbose_name="Status", null=True, blank=True)  
    class Invalidar_Secuencia(models.TextChoices):
        PROBLEMAS_EQUIPO_1 = "Problemas de equipo (Equipo presionado, Linea base defectuosa)", "PROBLEMAS_EQUIPO_1"
        PROBLEMAS_EQUIPO_2 = "Problemas de equipo (Otros: Caidas de presión, Picos fantasmas; Problemas de software/hadware...)", "PROBLEMAS_EQUIPO_2"
        PROBLEMAS_COLUMNA = "Problemas de columna", "PROBLEMAS_COLUMNA"
        INCUMPLIMIENTO_SST_1 = "Incumplimiento de System (RSD)", "INCUMPLIMIENTO_SST_1"
        INCUMPLIMIENTO_SST_2 = "Incumplimiento de System (Otros: Resolución, Asimetria, Platos teóricos, Señal ruido)", "INCUMPLIMIENTO_SST_2"
        INCUMPLIMIENTO_SST_3 = "Incumplimiento de System (Correlación)", "INCUMPLIMIENTO_SST_3"
        PROBLEMAS_FM = "Problemas de Fases Móviles (TR Corridos, FM saturada, Otros...)", "PROBLEMAS_DE_FASE_MOVIL"
        PROBLEMAS_RED = "Problemas de red", "PROBLEMAS_RED"
        PROBLEMAS_FE = "Fallas de Fluido Eléctrico", "PROBLEMAS_DE_FLUIDO_ELECTRICO"
        OTROS = "Otros (definir en observaciones)", "OTROS"
    invalidar_Secuencia=models.CharField(max_length=250, choices=Invalidar_Secuencia.choices, verbose_name="Invalidar Secuencia", null=True, blank=True)  
    class Condicion(models.TextChoices):
        ACTIVO = "Activo", "ACTIVO"
        PASIVO = "Pasivo", "PASIVO"
    condicion=models.CharField(max_length=90, choices=Condicion.choices, default=Condicion.ACTIVO, verbose_name="Condicion", null=True, blank=True)  
    observaciones=models.CharField(max_length=250, verbose_name="Observaciones",  null=True, blank=True)
    parametro_sq=models.ForeignKey(to=Parametro, on_delete=models.CASCADE, verbose_name="Parametro", null=True, blank=True)
    metodo=models.ForeignKey(to=Metodo, on_delete=models.CASCADE, verbose_name="Metodo", null=True, blank=True)
    #muestras=models.ManyToManyField(to=Muestras_y_Placebos, blank=False)
    muestras=models.ForeignKey(to=Muestras_y_Placebos, on_delete=models.CASCADE, verbose_name="Muestras", null=True, blank=True)
    fecha_invalidar=models.DateTimeField(verbose_name="Fecha de Invalidéz", null=True, blank=True)
    fecha_validar=models.DateTimeField(verbose_name="Fecha de Validación", null=True, blank=True)
    fecha_impresion=models.DateTimeField(verbose_name="Fecha de Impresión", null=True, blank=True)
    fecha_reporte=models.DateTimeField(verbose_name="Fecha de Reporte", null=True, blank=True)
    fecha_auditada=models.DateTimeField(verbose_name="Fecha auditada", null=True, blank=True)
    def individual():
     " This function will be called when a default value is needed.ll return a 31 length string with a-z, 0-9."
     return 'Prueba'
    #referencia=models.CharField(max_length=250, verbose_name="Referencia Reporte",  null=True, blank=True,default=individual)
    invalidar=models.CharField(max_length=250, verbose_name="Invalidada por",  null=True, blank=True)
    validar=models.CharField(max_length=250, verbose_name="Validada por",  null=True, blank=True)
    imprimir=models.CharField(max_length=250, verbose_name="Impresa",  null=True, blank=True)
    reportar=models.CharField(max_length=250, verbose_name="Reportada por",  null=True, blank=True)
    auditar=models.CharField(max_length=250, verbose_name="Auditada por",  null=True, blank=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['protocolo', 'parametro_sq', 'fecha_invalidar'], name='unique'),
            models.UniqueConstraint(fields=['protocolo_proceso', 'muestras', 'fecha_invalidar'], name='unique_intro_nue'),
        ]
    
    def nombre_Secuencia(self):
        return "{}".format(self.nombre)    
    def __str__(self):    

        return str(self.nombre_Secuencia())
    
    
class Lavado_buzo(models.Model):
    date_joined = datetime.datetime.now()
    progrmado = datetime.datetime.now() + datetime.timedelta(days=30) 
    limite_inferior = datetime.datetime.now() + datetime.timedelta(days=59.8) 
    limite_superior = datetime.datetime.now() + datetime.timedelta(days=60.9) 
    progrmado_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=60.8) 
    limite_inferior_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=5) 
    limite_superior_mantenimiento = datetime.datetime.now() + datetime.timedelta(days=7) 
    progrmado_calificacion = datetime.datetime.now() + datetime.timedelta(days=60.8)
    limite_inferior_calificacion = datetime.datetime.now() + datetime.timedelta(days=5)
    limite_superior_calificacion = datetime.datetime.now() + datetime.timedelta(days=7)
    sistema=models.ForeignKey(to=Sistema, on_delete=models.CASCADE, verbose_name="Sistema", null=True, blank=False)
    fecha_lavado_buzo=models.DateField(verbose_name="Fecha de lavado de buzos", null=True, blank=True, default=progrmado)
    fecha_lavado_celda=models.DateField(verbose_name="Fecha de lavado de celda", null=True, blank=True, default=progrmado)
    fecha_test_diagnostico=models.DateField(verbose_name="Fecha del test", null=True, blank=True, default=progrmado)
    fecha_mantenimiento=models.DateField(verbose_name="Fecha del Mantenimiento", null=True, blank=True, default=progrmado_mantenimiento) 
    fecha_calificacion=models.DateField(verbose_name="Fecha de la calificación", null=True, blank=True, default=progrmado_mantenimiento) 
    fecha_alerta_inferior=models.DateField(verbose_name="Fecha de alerta inferior", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior=models.DateField(verbose_name="Fecha de alerta superior", null=True, blank=True, default=limite_superior)
    fecha_alerta_inferior_celda=models.DateField(verbose_name="Fecha de alerta inferior celda", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior_celda=models.DateField(verbose_name="Fecha de alerta superior celda", null=True, blank=True, default=limite_superior)
    fecha_alerta_inferior_test=models.DateField(verbose_name="Fecha de alerta inferior test", null=True, blank=True, default=limite_inferior)
    fecha_alerta_superior_test=models.DateField(verbose_name="Fecha de alerta superior test", null=True, blank=True, default=limite_superior) 
    fecha_alerta_inferior_mantenimiento=models.DateField(verbose_name="Fecha de alerta inferior mantenimiento", null=True, blank=True, default=limite_inferior_mantenimiento) 
    fecha_alerta_superior_mantenimiento=models.DateField(verbose_name="Fecha de alerta superior mantenimiento", null=True, blank=True, default=limite_superior_mantenimiento) 

MONSTER_APP/templates/protocolo_proceso/crear_protocolo_proceso.html
{% extends "protocolo_metodos/base_crear_protocolo_metodos.html" %}
{% block contenido %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!--Advanced multiselect esasy-->
<script src="https://www.jqueryscript.net/demo/advanced-multiselect-easy/easySelect.js"></script>
  <div class="container-fluid"><br>
    
    
           <!-- Using a local copy -->

<!-- Include the default stylesheet -->


<!-- Or using a CDN -->

<!-- Include the default stylesheet -->
   
            
    <div class="row">
        <!---------------------------------------Inicio Columna 1------------------------------------------------------>
      <div class="">
        <div class="card col-12 col-lg-7" style="background-color: #1b3d70c2;margin: auto;">
          <h5 class="text-white text-center"><br>Crear Protocolo de Proceso</h5>
     </div>
        <div class="card col-12 col-lg-7" style="margin: auto;">
          <div class="row gy-1 gy-xl-2 p-4 p-xl-4">
            <form action=""  id="myModelForm" method="POST">
              {% csrf_token %}
                   
              <div class="row">
                <div class="col-md-6">
                    {{ form.fecha_ingreso|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                    {{ form.codigo|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                    {{ form.cliente|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  {{ form.metodo|as_crispy_field  }}
              </div>
               
              </div>
              <div class="row">
                <div class="col-md-6">
                    {{ form.celda|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                    {{ form.metodologia|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
             
                <div class="col-md-12">
                    {{ form.estado_del_proceso|as_crispy_field  }}
                </div>
              </div>
              <div class="col-md-12">
                {{ form.ensayos|as_crispy_field  }}
            </div>
              {{ form.nombre|as_crispy_field  }}
              

              {{ form.Insumos_del_Proceso|as_crispy_field  }}
            <div class="card col-md-12" >
                {{ form.muestras|as_crispy_field  }}
            </div>
           
            {{ form.observaciones|as_crispy_field  }}
            <div class="modal-footer">
              <a href="{% url 'muestras' %}" onclick='salir(event)' style="background-color: #7d848ec2;" class="btn btn-dark" >Cancelar</a>
              <button type="submit" onclick='confirmar(event)' class="btn btn-primary" style="background-color: #1b3d70c2;" >Guardar</button>
            </div>
          </div>
          
        </div>
      </div>
      <!---------------------------------------------Inicio Columna 2------------------------------------------------------>
     
    
       
    </form>
    {% block scripts %}
    <script>
      $("#id_ensayos").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_metodo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
     
$("#id_cliente").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
    </script>
<script> 
$(document).ready(function() {
$('#id_muestras').css('width', '100%').multiselect(
{
enableFiltering: true,
filterBehavior: 'text',
buttonWidth: '100%',
enableClickableOptGroups: true,
enableCollapsibleOptGroups: true,
nonSelectedText: 'Seleccionar muestras',
enableCaseInsensitiveFiltering: true,
includeSelectAllOption: true,
maxHeight: 300
}
);
});
</script>
     {% endblock scripts %}
  </div>
</div>

<!-- Validación de campos -->
<script>
function confirmar(event) { 
  
  event.preventDefault();
  Swal.fire({
title: "Está seguro?",
text: "Por favor, confirme la creación del protocolo!",
icon: "question",
showCancelButton: true,
confirmButtonColor: "#3085d6",
cancelButtonColor: "#d33",
confirmButtonText: "Confirmar!"
  }).then((result) => {
      if (result.isConfirmed) {
        document.getElementById('myModelForm').submit();
      }
  })
}
</script>
<script>
function salir(event) { 
  
  event.preventDefault();
  Swal.fire({
title: "Desea salir?",
text: "Tu información no será guardada!",
icon: "warning",
showCancelButton: true,
confirmButtonColor: "#3085d6",
cancelButtonColor: "#d33",
confirmButtonText: "Confirmar",
cancelButtonText: "Cancelar"
}).then((result) => {
      if (result.isConfirmed) {
        window.location.href = '/adm_inicio'
      }
  })
}
</script>



<!-- validacion de campos-->

<!--
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>  
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" rel="stylesheet"/>
{% endblock contenido %}

MONSTER_APP/templates/protocolo_proceso/edicion_protocolo_proceso.html
{% extends "protocolo_metodos/base_crear_protocolo_metodos.html" %}
{% block contenido %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!--Advanced multiselect esasy-->
<script src="https://www.jqueryscript.net/demo/advanced-multiselect-easy/easySelect.js"></script>
  <div class="container-fluid"><br>
    
    
           <!-- Using a local copy -->

<!-- Include the default stylesheet -->


<!-- Or using a CDN -->

<!-- Include the default stylesheet -->
   
            
    <div class="row">
        <!---------------------------------------Inicio Columna 1------------------------------------------------------>
      <div class="">
        <div class="card col-12 col-lg-7" style="background-color: #1b3d70c2;margin: auto;">
          <h5 class="text-white text-center"><br>Editar Protocolo de Proceso</h5>
     </div>
        <div class="card col-12 col-lg-7" style="margin: auto;">
          <div class="row gy-1 gy-xl-2 p-4 p-xl-4">
            <form action=""  id="myModelForm" method="POST">
              {% csrf_token %}
                   
              <div class="row">
                <div class="col-md-6">
                    {{ form.fecha_ingreso|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                    {{ form.codigo|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                    {{ form.cliente|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                  <div id="div_id_fecha_final" class="mb-3">
                    <label for="id_fecha_final" class="form-label requiredField">
                        Fecha del estado<span class="asteriskField">*</span>
                    </label>
                  <input type="date" name="fecha_final" class="numberinput form-control" required id="id_fecha_final">
                </div>
                </div>
              
              </div>
              <div class="row">
                <div class="col-md-6">
                    {{ form.celda|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                    {{ form.metodologia|as_crispy_field  }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                    {{ form.metodo|as_crispy_field  }}
                </div>
                <div class="col-md-6">
                    {{ form.estado_del_proceso|as_crispy_field  }}
                </div>
              </div>
              {{ form.nombre|as_crispy_field  }}
              

              {{ form.Insumos_del_Proceso|as_crispy_field  }}
            <div class="card col-md-12" >
                {{ form.muestras|as_crispy_field  }}
            </div>
            <div class="col-md-12">
              {{ form.ensayos|as_crispy_field  }}
          </div>
           
            {{ form.observaciones|as_crispy_field  }}
          
  
            <div class="modal-footer">
              <a href="{% url 'protocolo_proceso' %}" onclick='salir(event)' style="background-color: #7d848ec2;" class="btn btn-dark" >Cancelar</a>
              <button type="submit" onclick='confirmar(event)' class="btn btn-primary" style="background-color: #1b3d70c2;" >Guardar</button>
            </div>
          </div>
          
        </div>
      </div>
    </form>
    {% block scripts %}
   <script>
    $("#id_ensayos").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
$("#id_metodo").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
   
$("#id_cliente").select2({
theme: "bootstrap-5",
placeholder: "Seleccione",
});
  </script>
<script> 
$(document).ready(function() {
$('#id_muestras').css('width', '100%').multiselect(
{
enableFiltering: true,
filterBehavior: 'text',
buttonWidth: '100%',
enableClickableOptGroups: true,
enableCollapsibleOptGroups: true,
nonSelectedText: 'Seleccionar muestras',
enableCaseInsensitiveFiltering: true,
includeSelectAllOption: true,
maxHeight: 300
}
);
});
</script>



 <!-- Validación de campos -->
<script>
  function confirmar(event) { 
    let x = document.forms["myModelForm"]["fecha_final"].value;
 if (x == "") {
 
alert("Se requiere fecha final del estado");
 e.preventDefault();
   } 
    event.preventDefault();
    Swal.fire({
  title: "Está seguro?",
  text: "Por favor, confirme la edición del protocolo!",
  icon: "question",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Editar!"
    }).then((result) => {
        if (result.isConfirmed) {
          document.getElementById('myModelForm').submit();
        }
    })
}
</script>
<script>
  function salir(event) { 
    
    event.preventDefault();
    Swal.fire({
  title: "Desea salir?",
  text: "Tu información no será guardada!",
  icon: "warning",
  showCancelButton: true,
  confirmButtonColor: "#3085d6",
  cancelButtonColor: "#d33",
  confirmButtonText: "Confirmar",
  cancelButtonText: "Cancelar"
}).then((result) => {
        if (result.isConfirmed) {
          window.location.href = '/protocolo_proceso'
        }
    })
}
</script>
  <!-- validacion de campos-->

   {% endblock scripts %}
   <!--
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
   -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" rel="stylesheet"/>
  {% endblock contenido %}